# Generated by Django 5.1.15 on 2026-06-28 18:11

import apps.feedback.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_number', models.CharField(default=apps.feedback.models.generate_feedback_number, max_length=30, unique=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reporter_type', models.CharField(blank=True, max_length=30)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('BUG', 'Bug Report'), ('FEATURE', 'Feature Request'), ('IMPROVEMENT', 'Improvement Suggestion'), ('PERFORMANCE', 'Performance Issue'), ('UI_UX', 'UI/UX Issue'), ('SECURITY', 'Security Concern'), ('CONTENT', 'Content Correction'), ('COURSE', 'Course Feedback'), ('ACHARYA', 'Acharya Feedback'), ('COMPLAINT', 'Complaint'), ('APPRECIATION', 'Appreciation')], default='BUG', max_length=30)),
                ('source_module', models.CharField(choices=[('ADMISSIONS', 'Admissions'), ('STUDENTS', 'Students'), ('LMS', 'Learning / LMS'), ('ATTENDANCE', 'Attendance'), ('CURRICULUM', 'Curriculum'), ('HOSTEL', 'Hostel'), ('DONATIONS', 'Donations'), ('COMMUNITY', 'Community'), ('ALUMNI', 'Alumni'), ('MOBILE', 'Mobile App'), ('PLATFORM', 'Platform / General')], default='PLATFORM', max_length=30)),
                ('environment', models.CharField(choices=[('LOCAL', 'Local'), ('DEV', 'Development'), ('QA', 'QA'), ('UAT', 'UAT'), ('PRODUCTION', 'Production')], default='PRODUCTION', max_length=20)),
                ('platform', models.CharField(choices=[('WEB', 'Web'), ('ANDROID', 'Android'), ('IOS', 'iOS')], default='WEB', max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=30)),
                ('browser_device', models.CharField(blank=True, max_length=255)),
                ('screen_name', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('steps_to_reproduce', models.TextField(blank=True)),
                ('expected_result', models.TextField(blank=True)),
                ('actual_result', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('AI_ANALYZED', 'AI Analyzed'), ('DUPLICATE_LINKED', 'Linked to Duplicate'), ('PENDING_APPROVAL', 'Pending Manual Approval'), ('GITHUB_CREATED', 'GitHub Issue Created'), ('IN_PROGRESS', 'In Progress'), ('TESTING', 'Testing'), ('RELEASED', 'Released'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('priority', models.CharField(choices=[('P4', 'P4 – Low'), ('P3', 'P3 – Normal'), ('P2', 'P2 – High'), ('P1', 'P1 – Urgent')], default='P3', max_length=5)),
                ('assigned_team', models.CharField(blank=True, max_length=100)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='feedback.feedback')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('ai_category', models.CharField(blank=True, max_length=30)),
                ('ai_summary', models.TextField(blank=True)),
                ('root_cause_suggestion', models.TextField(blank=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recommended_priority', models.CharField(blank=True, max_length=5)),
                ('recommended_team', models.CharField(blank=True, max_length=100)),
                ('create_github_issue', models.BooleanField(default=False)),
                ('github_issue_draft', models.TextField(blank=True)),
                ('raw_analysis', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='feedback.feedback')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('s3_bucket', models.CharField(blank=True, max_length=100)),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('is_screenshot', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedback')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedback')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='feedback.feedback')),
            ],
            options={
                'verbose_name_plural': 'feedback histories',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='GitHubIssueMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('issue_number', models.PositiveIntegerField(db_index=True)),
                ('issue_url', models.URLField(max_length=500)),
                ('repo', models.CharField(max_length=200)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('state', models.CharField(default='open', max_length=30)),
                ('created_by_system', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_issue', to='feedback.feedback')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status', 'created_at'], name='feedback_fe_status_91deca_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['source_module', 'status'], name='feedback_fe_source__93429d_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['environment', 'priority'], name='feedback_fe_environ_dc4a5d_idx'),
        ),
    ]
