# Generated by Django 5.1.15 on 2026-06-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubissuemapping',
            name='api_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='githubissuemapping',
            name='http_status',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubissuemapping',
            name='sync_mode',
            field=models.CharField(choices=[('STUB', 'Demo / stub (not in GitHub)'), ('REAL', 'Created in GitHub'), ('FAILED', 'GitHub API failed')], default='STUB', max_length=10),
        ),
    ]
