# Generated by Django 5.1.15 on 2026-06-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('ACHARYA', 'Acharya'), ('BRANCH_ADMIN', 'Branch Admin'), ('SUPER_ADMIN', 'Super Admin'), ('DONOR', 'Donor'), ('HOSTEL_WARDEN', 'Hostel Warden'), ('ALUMNI', 'Alumni')], db_index=True, max_length=20),
        ),
    ]
