# Generated by Django 5.1.15 on 2026-06-28 18:41

import apps.gurukulam_feedback.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GurukulamFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_number', models.CharField(default=apps.gurukulam_feedback.models.generate_gurukulam_feedback_number, max_length=30, unique=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reporter_type', models.CharField(blank=True, max_length=30)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('TEACHING', 'Teaching & Curriculum'), ('FACILITIES', 'Facilities & Infrastructure'), ('ADMINISTRATION', 'Administration & Communication'), ('EVENTS', 'Events & Programs'), ('HOSTEL', 'Hostel & Mess'), ('SUGGESTION', 'Suggestion'), ('COMPLAINT', 'Complaint'), ('APPRECIATION', 'Appreciation')], default='SUGGESTION', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gurukulam_feedback_submissions', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gurukulam_feedback_responses', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GurukulamFeedbackHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='gurukulam_feedback.gurukulamfeedback')),
            ],
            options={
                'verbose_name_plural': 'gurukulam feedback histories',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gurukulamfeedback',
            index=models.Index(fields=['status', 'created_at'], name='gurukulam_f_status_6f9205_idx'),
        ),
        migrations.AddIndex(
            model_name='gurukulamfeedback',
            index=models.Index(fields=['category', 'status'], name='gurukulam_f_categor_8c5c36_idx'),
        ),
    ]
