# Generated by Django 5.1.15 on 2026-06-28 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admissionapplication_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Reason shared with applicant for reject/resubmit.'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_application_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='upload_status',
            field=models.CharField(choices=[('PENDING', 'Pending Upload'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('RESUBMIT_REQUESTED', 'Resubmit Requested')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationnotification',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationnotification',
            name='event_type',
            field=models.CharField(choices=[('APPLICATION_PENDING', 'Application Pending Review'), ('APPLICATION_APPROVED', 'Application Approved'), ('APPLICATION_REJECTED', 'Application Rejected'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('DOCUMENT_RESUBMIT_REQUESTED', 'Document Resubmit Requested')], max_length=30),
        ),
        migrations.CreateModel(
            name='ApplicationDocumentReviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=30)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('notified_channels', models.JSONField(blank=True, default=list)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_review_logs', to='admissions.admissionapplication')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_review_actions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='admissions.applicationdocument')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
